const initialState = [
{ category : 'shoes',
brand : 'Asics',
photo: "as1.jpg",
title: 'Asics Sky Elite FF MT "Tokyo"',
price: 399,
desciption: "",
id: "1",
promoted: true,
size : ['41','42','43','45', '47'],
color : ['red'],
filterProperties : []

},
{ category : 'shoes',
photo: "miz1.jpg",
brand : 'Mizuno',
title: "Mizuno Wave Momentum",
price: 399,
desciption: "",
id: "1",
promoted: true,
size : ['41','42','43','46','49'],
color : [ 'red', 'black'],
filterProperties : []
},
{ category : 'shoes',
brand : 'Mizuno',
photo: "miz2.jpg",
title: "Mizuno Wave Lightning Neo",
price: 399,
desciption: "",
id: "1",
promoted: true,
size : ['41','42','43'],
color : [ 'black'],
filterProperties : []
},
{ category : 'shoes',
brand : 'Nike',
photo: "nk1.jpg",
title: "Nike Air Zoom Hyperace 2",
price: 399,
desciption: "",
id: "1",
promoted: true,
size : ['38','39','40','45','42','43'],
color : [ 'white'],
filterProperties : []
},
{ category : 'shoes',
brand : 'Nike',
photo: "nk1.jpg",
title: "Nike Air Zoom Hyperace 2",
price: 399,
desciption: "",
id: "1",
promoted: false,
size : ['41','42'],
color : [ 'white'],
filterProperties : []
},
{ category : 'shoes',
brand : 'Adidas',
photo: "adi4.jpg",
title: "Adidas Harden Vol.4 J x Star Wars Lightsaber",
price: 399,
desciption: "",
id: "1",
promoted: false,
size : ['41','42','43', '40'],
color : [ 'black', 'purple'],
filterProperties : []
},
{ category : 'shoes',
brand : 'Adidas',
photo: "adi3.jpg",
title: "Adidas Harden Vol. 4",
price: 399,
desciption: "",
id: "1",
promoted: false,
size : ['48','42','43'],
color : [ 'white'],
filterProperties : []
},
{ category : 'shoes',
brand : 'Adidas',
photo: "adi2.jpg",
title: "adidas Harden Vol. 5 Futurenatural Volt Pink Navy",
price: 399,
desciption: "",
id: "1",
promoted: false,
size : ['46','39','43'],
color : [ 'yellow'],
filterProperties : []
},
{ category : 'shoes',
brand : 'Adidas',
photo: "adi1.jpg",
title: "Adidas Harden Vol. 5 Futurenatural",
price: 399,
desciption: "",
id: "1",
promoted: false,
size : ['37','38','39','40'],
color : [ 'pink', 'black'],
filterProperties : []
},
{ category : 'shoes',
brand : 'Mizuno',
photo: "miz3.jpg",
title: "Mizuno Wave Momentum 2",
price: 399,
desciption: "",
id: "1",
promoted: false,
size : ['38','45','39', '40', '41'], 
color : [ 'white','pink'],
filterProperties : []
},
{ category : '',
brand : 'Asics',
photo: "as2.jpg",
title: "Asics Netburner Ballistic FF",
price: 399,
desciption: "",
id: "1",
promoted: false,
size : ['38','45','51'],
color : [ 'black', 'blue','green'],
filterProperties : []
},
{ 
category : 'shoes',
brand : 'Asics',
photo: "as3.jpg",
title: "Asics Gel-Task",
price: 399,
desciption: "",
id: "1",
promoted: false,
size : ['38','45','51'],
color : [  'blue'],
filterProperties : []
},
{
    category : 'shirts',
    photo: "products photo/shirts/k1.jpg",
    title: "Nike Air Zoom Hyperace 2",
    price: 399,
    desciption: "",
    id: "1",
    promoted: true,
    size : ['M','L','XL'],
    color : ['red']
  },
  {
    category : 'shirts',
    photo: "products photo/shirts/k4.jpg",
    title: "Adidas Essentials Linear T-shirt",
    price: 79.99,
    desciption: "",
    id: "1",
    promoted: true,
    size : ['M','L','XL'],
    color : ['white']
  },
  {
    category : 'shirts',
    photo: "products photo/shirts/k3.jpg",
    title: "Koszulka adidas ESS 3S Tee",
    price: 99.99,
    desciption: "",
    id: "1",
    promoted: true,
    size : ['M','L','XL'],
    color : ['gray']
  },
  {
    category : 'shirts',
    brand : 'Adidas',
    photo: "products photo/shirts/k2.jpg",
    title: "Adidas Trefoil Essentials Tee",
    price: 399,
    desciption: "",
    id: "1",
    promoted: true,
    size : ['M','L','XL'],
    color: ['black']
  },
  {
    category : 'shirts',
    brand: 'Adidas',
    photo: "products photo/bluzy/adi1.jpg",
    title: "Adidas Essentials Logo Hoodie Grey",
    price: 139.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : ['M','L','XL','XXL'],
    color: ['gray']
  },
  {
    category : 'shirts',
    brand: 'Adidas',
    photo: "products photo/bluzy/adi2.jpg",
    title: "adidas Trefoil Hoodie",
    price: 139.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : ['L','XL','XXL'],
    color: ['black']
  },
  {
    category : 'shirts',
    brand: 'Adidas',
    photo: "products photo/bluzy/adi3.jpg",
    title: "Adidas Trefoil Hoodie Męska Czerwona",
    price: 139.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : ['L','XL','XXL'],
    color: ['red']
  },
  {
    category : 'shirts',
    brand: 'Reebok',
    photo: "products photo/spodnie/s1.jpg",
    title: "Reebok Training Essentials Marble",
    price: 139.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : ['L','XL','XXL'],
    color: ['gray']
  },
  {
    category : 'shirts',
    brand: 'Adidas',
    photo: "products photo/spodnie/s2.jpg",
    title: "Adidas Trefoil Pant",
    price: 139.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : ['L','XL','XXL'],
    color: ['black']
  },
  {
    category : 'accessories',
    brand: 'Adidas',
    photo: "products photo/akcesoria/cz1.jpg",
    title: "Czapka adidas 3S Cap",
    price: 139.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : [],
    color: ['red']
  },
  {
    category : 'accessories',
    brand: 'Adidas',
    photo: "products photo/akcesoria/s1.jpg",
    title: "Adidas Treofil Liner 3 Pack",
    price: 39.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : [],
    color: ['white']
  },
  {
    category : 'accessories',
    brand: 'Cep',
    photo: "products photo/akcesoria/s2.jpg",
    title: "Cep Socks For Recovery 2.0 M",
    price: 99.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : [],
    color: ['black']
  },
  {
    category : 'accessories',
    brand: 'Adidas',
    photo: "products photo/akcesoria/t1.jpg",
    title: "Adidas Tiro Dufflebag M",
    price: 99.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : [],
    color: ['black']
  },
  {
    category : 'accessories',
    brand: 'Nike',
    photo: "products photo/akcesoria/t2.jpg",
    title: "Nike Brasilia Training Duffel Bag",
    price: 99.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : [],
    color: ['red']
  },
  {
    category : 'accessories',
    brand: 'Adidas',
    photo: "products photo/akcesoria/t3.jpg",
    title: "Adidas Adicolor Classic Backpack ",
    price: 99.99,
    desciption: "",
    id: "1",
    promoted: false,
    size : [],
    color: ['red']
  },
  


    ]


const ProductDB = (state = [], action) => {
    switch(action.type){
        case 'SET_PRODUCTS' : return action.payload;
        default : return initialState
    }
    
}

export default ProductDB